language: php
php:
  - '7.1'
  - '7.2'
  - nightly
before_script:
  - composer install
  - cp .env.example .env
  - echo "APP_ENV=test" >> .env
  - php artisan key:generate
after_script:
  - php vendor/bin/codacycoverage clover report/clover/clover.xml
