env:
  global:
    - CC_TEST_REPORTER_ID=327363970807447261fcd691a1e3332a76691a3bcfb55d276d38d6b35b312993
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
before_script:
  - composer install
  - cp .env.example .env
  - echo "APP_ENV=test" >> .env
  - php artisan key:generate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT